### ISSUE TITLE
Consider using queue interprop as abstraction for queues

### ISSUE THREAD

**Issue by makasim** [AudienceHero/AudienceHero#1]
Hello!

Please look at https://github.com/queue-interop/queue-interop project. Using interfaces from it allows us reuse some implementations like enqueue, which supports a lot of transports. You can outsource some code

**Comment by marcw** [comment]
Hey, thanks for opening an issue (the first!) on that matter. This is a good suggestion but it's unfortunately not my priority right now. I'll consider it at some point. Until then, feel free to open a PR with the needed changes.
