### ISSUE TITLE
How to install AudienceHero/ImageServerBundle?

### ISSUE THREAD

**Issue by homeandr777** [AudienceHero/AudienceHero#2]
Hello,

I can not install the AudienceHero bundle, that you are using in UploadAction.php file.

composer require audience-hero/image-server-bundle "~1"

I tried all composer options, it is just not working.

Could not find a matching version of package audience-hero/image-server-bundle. Check the package spelling, your version constraint and that the package is available in a stability which matches your minimum-stability (stable).  

Could you fix the bundle?

**Comment by marcw** [comment]
Hi! At present time, the bundles cannot be installed independently.
